---
- name: Install Jenkins
  hosts: all
  become: true

  tasks:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
        update_cache: yes

    - name: Install Java (Jenkins requirement)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins GPG key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      args:
        executable: /bin/bash

    - name: Add Jenkins apt repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      args:
        executable: /bin/bash

    - name: Update apt cache explicitly
      shell: apt-get update
      args:
        executable: /bin/bash

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
